version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.17.21
    restart: always
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data

  db:
    build:
      context: database
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_DB: tripcraft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./countries-states-cities-database/psql/world.sql:/docker-entrypoint-initdb.d/world.sql

  server:
    build:
      context: server
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    env_file:
      - ./server/.env
    depends_on:
      - db
      - elasticsearch
    volumes:
      - ./server:/usr/src/app

  portal:
    build:
      context: portal
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - server
    volumes:
      - /usr/src/app/node_modules
      - ./portal:/usr/src/app

volumes:
  db_data:
  es_data:
